import type { RefineResponse } from './types'

export type LaudoLang = 'pt' | 'en'

export interface LaudoMeta {
  languageName: string
  original: string
  translation: string
  source?: string
  title?: string
  lang?: LaudoLang
}

const FLAG_LABEL: Record<LaudoLang, Record<string, string>> = {
  pt: {
    hapax: 'Hapax legomenon', semantic_narrowing: 'Estreitamento semântico',
    consensus_low: 'Baixo consenso', intra_inconsistent: 'Inconsistência intra-documento',
    contested_semantics: 'Semântica contestada', lacuna: 'Lacuna', idiomatic: 'Idiomático',
  },
  en: {
    hapax: 'Hapax legomenon', semantic_narrowing: 'Semantic narrowing',
    consensus_low: 'Low consensus', intra_inconsistent: 'Intra-document inconsistency',
    contested_semantics: 'Contested semantics', lacuna: 'Lacuna', idiomatic: 'Idiomatic',
  },
}

const T: Record<LaudoLang, Record<string, string>> = {
  pt: {
    title: 'Laudo Filológico', untitled: 'Passagem sem título', language: 'Idioma',
    original: 'Texto original', audited: 'Tradução auditada', date: 'Data',
    processing: 'Processamento', analysis: 'análise', verdict: 'Veredito',
    noVerdict: '_(veredito não gerado)_', synthesis: 'Síntese',
    tokens: 'Tokens analisados', flagged: 'sinalizados', avgConf: 'Confiança média',
    high: 'alta', low: 'baixa', flags: 'Flags', none: 'nenhuma',
    inconsist: 'Inconsistências intra-documento', renderedAs: 'traduzido como',
    perToken: 'Análise por token',
    cols: '| # | Original | Translit. | Existente | Refinada | Conf. | Flags | Léxico (citação) | Consenso |',
    method: 'Metodologia e limites',
    m1: '**Léxico:** {lex}. Cada glosa traz citação verificável.',
    m2: '**Consenso:** fração de autoridade ponderada das traduções de referência que concordam. **Provisório (derivado por LLM)** — a ser substituído por corpus alinhado verificado.',
    m3: '**Confiança:** métrica objetiva (léxico + consenso + hapax + controvérsia), não opinião do modelo.',
    m4: 'O veredito sintetiza os achados acima; não introduz afirmações fora deles.',
    origLabel: 'ORIGINAL', transLabel: 'TRADUÇÃO', corrLabel: 'CORREÇÕES SUGERIDAS',
    noCorr: 'Nenhuma correção sugerida — a tradução é consistente com o léxico e o consenso.',
    consensusWord: 'consenso',
    footer: '_Gerado por HERMENEIA — auditor filológico de traduções._',
  },
  en: {
    title: 'Philological Audit Report', untitled: 'Untitled passage', language: 'Language',
    original: 'Source text', audited: 'Translation audited', date: 'Date',
    processing: 'Processing', analysis: 'analysis', verdict: 'Verdict',
    noVerdict: '_(verdict not generated)_', synthesis: 'Summary',
    tokens: 'Tokens analyzed', flagged: 'flagged', avgConf: 'Average confidence',
    high: 'high', low: 'low', flags: 'Flags', none: 'none',
    inconsist: 'Intra-document inconsistencies', renderedAs: 'rendered as',
    perToken: 'Token-by-token analysis',
    cols: '| # | Original | Translit. | Existing | Refined | Conf. | Flags | Lexicon (citation) | Consensus |',
    method: 'Methodology and limits',
    m1: '**Lexicon:** {lex}. Every gloss carries a verifiable citation.',
    m2: '**Consensus:** weighted authority share of reference translations agreeing with each rendering. **Provisional (LLM-derived)** — to be replaced by a verified aligned corpus.',
    m3: '**Confidence:** objective metric (lexicon + consensus + hapax + controversy), not model opinion.',
    m4: 'The verdict synthesizes the findings above; it introduces nothing beyond them.',
    origLabel: 'ORIGINAL', transLabel: 'TRANSLATION', corrLabel: 'SUGGESTED CORRECTIONS',
    noCorr: 'No corrections suggested — the translation is consistent with lexicon and consensus.',
    consensusWord: 'consensus',
    footer: '_Generated by HERMENEIA — philological translation auditor._',
  },
}

const _ARTICLES = new Set(['the', 'a', 'an', 'o', 'os', 'as', 'um', 'uma'])

function _cleanSuggestion(s: string): string {
  return (s || '').split(/[(;\n]/)[0].trim().replace(/^["']|["',.]$/g, '').trim()
}

const LEXICON_BY_LANG: Record<string, string> = {
  'Biblical Hebrew': 'BDB (Brown-Driver-Briggs)',
  'Koine Greek': 'LSJ (Liddell-Scott-Jones)',
  'Classical Greek': 'LSJ (Liddell-Scott-Jones)',
  'Classical Latin': 'Lewis & Short',
}

function esc(s: string): string {
  return (s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

export function buildLaudo(meta: LaudoMeta, r: RefineResponse): string {
  const lang: LaudoLang = meta.lang ?? 'pt'
  const t = T[lang]
  const fl = FLAG_LABEL[lang]
  const s = r.summary
  const date = new Date().toISOString().slice(0, 16).replace('T', ' ')
  const lex = LEXICON_BY_LANG[meta.languageName] ?? (lang === 'pt' ? 'léxico de referência' : 'reference lexicon')

  const L: string[] = []
  L.push(`# ${t.title} — ${meta.title || t.untitled}`)
  L.push('')
  L.push(`- **${t.language}:** ${meta.languageName}`)
  L.push(`- **${t.original}${meta.source ? ` (${meta.source})` : ''}:** ${meta.original}`)
  L.push(`- **${t.audited}${meta.source ? ` — ${meta.source}` : ''}:** ${meta.translation}`)
  L.push(`- **${t.date}:** ${date}`)
  L.push(`- **${t.processing}:** ${r.processing_ms} ms · ${t.analysis} ${r.analysis_id}`)
  L.push('')

  L.push(`## ${t.verdict}`)
  L.push(s.narrative?.trim() || t.noVerdict)
  L.push('')

  L.push(`## ${t.synthesis}`)
  L.push(`- ${t.tokens}: **${s.total_tokens}** · ${t.flagged}: **${s.tokens_flagged}**`)
  L.push(`- ${t.avgConf}: **${(s.avg_confidence * 100).toFixed(0)}%** · ${t.high} (>75%): ${s.high_confidence_pct}% · ${t.low} (<50%): ${s.low_confidence_pct}%`)
  const fb = Object.entries(s.flags_breakdown)
  L.push(`- ${t.flags}: ${fb.length ? fb.map(([k, v]) => `${fl[k] ?? k} (${v})`).join(' · ') : t.none}`)
  L.push('')

  if (s.consistency_issues.length) {
    L.push(`## ${t.inconsist}`)
    for (const ci of s.consistency_issues) {
      L.push(`- \`${ci.token}\` (${ci.occurrences}×) ${t.renderedAs}: ${ci.translations_used.map(x => `"${x}"`).join(', ')}`)
    }
    L.push('')
  }

  L.push(`## ${t.perToken}`)
  L.push(t.cols)
  L.push('|---|---|---|---|---|---|---|---|---|')
  r.tokens.forEach((tok, i) => {
    const ev = tok.lexicon_evidence?.[0]
    const cite = ev ? `${esc(ev.gloss_primary)} [${esc(ev.source_citation || ev.lexicon)}]` : '—'
    const cons = tok.sources_total ? `${tok.sources_agreeing.length}/${tok.sources_total}` : '—'
    const refined = tok.refined && tok.refined !== tok.existing ? esc(tok.refined) : '='
    const flags = tok.flags.length ? tok.flags.map(f => fl[f] ?? f).join(', ') : '✓'
    L.push(`| ${i + 1} | ${esc(tok.original)} | ${esc(tok.transliteration || '')} | ${esc(tok.existing || '∅')} | ${refined} | ${(tok.confidence * 100).toFixed(0)}% | ${flags} | ${cite} | ${cons} |`)
  })
  L.push('')

  L.push(`## ${t.method}`)
  L.push(`- ${t.m1.replace('{lex}', lex)}`)
  L.push(`- ${t.m2}`)
  L.push(`- ${t.m3}`)
  L.push(`- ${t.m4}`)
  L.push('')

  // ── Bloco final acionável: ORIGINAL / TRADUÇÃO / CORREÇÕES SUGERIDAS ──
  const seen = new Set<string>()
  const corrections: string[] = []
  for (const tok of r.tokens) {
    if (!tok.flags.length) continue  // só corrige o que foi sinalizado
    const sug = _cleanSuggestion(tok.refined)
    const ex = (tok.existing || '').trim()
    if (!sug || sug.length > 30) continue
    if (sug.toLowerCase() === ex.toLowerCase()) continue
    if (_ARTICLES.has(sug.toLowerCase())) continue
    const orig = tok.original.replace(/[·.,;:!?]+$/g, '')
    const key = `${orig}|${ex.toLowerCase()}|${sug.toLowerCase()}`
    if (seen.has(key)) continue
    seen.add(key)
    const reasons = tok.flags.map(f => fl[f] ?? f)
    if (tok.sources_total && tok.sources_agreeing.length / tok.sources_total < 0.5) {
      reasons.push(`${t.consensusWord} ${tok.sources_agreeing.length}/${tok.sources_total}`)
    }
    const why = reasons.length ? ` — ${reasons.join(', ')}` : ''
    corrections.push(`- **${esc(orig)}**: "${esc(ex || '∅')}" → "${esc(sug)}"${why}`)
  }

  L.push('---')
  L.push(`**${t.origLabel}:** ${meta.original}`)
  L.push('')
  L.push(`**${t.transLabel}:** ${meta.translation}`)
  L.push('')
  L.push(`**${t.corrLabel}:**`)
  if (corrections.length) {
    L.push(...corrections)
  } else {
    L.push(t.noCorr)
  }
  L.push('')
  L.push(t.footer)

  return L.join('\n')
}

function _escHtml(s: string): string {
  return (s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

function _inline(s: string): string {
  return _escHtml(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
}

function _mdToHtml(md: string): string {
  const lines = md.split('\n')
  const out: string[] = []
  let i = 0
  let inList = false
  const closeList = () => { if (inList) { out.push('</ul>'); inList = false } }
  const parseRow = (r: string) =>
    r.replace(/^\||\|$/g, '').split(/(?<!\\)\|/).map(c => c.trim().replace(/\\\|/g, '|'))
  while (i < lines.length) {
    const line = lines[i]
    if (line.startsWith('|')) {
      const rows: string[] = []
      while (i < lines.length && lines[i].startsWith('|')) { rows.push(lines[i]); i++ }
      closeList()
      const header = parseRow(rows[0])
      const body = rows.slice(1).filter(r => !/^\|[-\s|]+\|?$/.test(r))
      out.push('<table><thead><tr>' + header.map(h => `<th>${_inline(h)}</th>`).join('') + '</tr></thead><tbody>')
      for (const br of body) out.push('<tr>' + parseRow(br).map(c => `<td>${_inline(c)}</td>`).join('') + '</tr>')
      out.push('</tbody></table>')
      continue
    }
    if (line.startsWith('## ')) { closeList(); out.push(`<h2>${_inline(line.slice(3))}</h2>`) }
    else if (line.startsWith('# ')) { closeList(); out.push(`<h1>${_inline(line.slice(2))}</h1>`) }
    else if (line.trim() === '---') { closeList(); out.push('<hr/>') }
    else if (line.startsWith('- ')) { if (!inList) { out.push('<ul>'); inList = true } out.push(`<li>${_inline(line.slice(2))}</li>`) }
    else if (line.trim() === '') { closeList() }
    else { closeList(); out.push(`<p>${_inline(line)}</p>`) }
    i++
  }
  closeList()
  return out.join('\n')
}

const _PRINT_CSS = `
@page { size: A4; margin: 18mm; }
body { font-family: "Times New Roman", Georgia, "SBL Hebrew", serif; font-size: 11pt; line-height: 1.5; color: #111; max-width: 800px; margin: 24px auto; padding: 0 16px; }
h1 { font-size: 17pt; margin: 0 0 4px; }
h2 { font-size: 13pt; border-bottom: 1px solid #ccc; padding-bottom: 3px; margin: 20px 0 8px; }
table { border-collapse: collapse; width: 100%; font-size: 9.5pt; margin: 8px 0; }
th, td { border: 1px solid #bbb; padding: 4px 6px; text-align: left; vertical-align: top; }
th { background: #f0f0f0; }
hr { border: none; border-top: 2px solid #333; margin: 16px 0; }
ul { margin: 6px 0; padding-left: 20px; }
p { margin: 6px 0; }
em { color: #555; }
@media print { body { margin: 0; } a { color: #000; } }
`

export function buildLaudoHtml(meta: LaudoMeta, r: RefineResponse): string {
  const lang: LaudoLang = meta.lang ?? 'pt'
  const head = (lang === 'pt' ? 'Laudo Filológico' : 'Philological Audit Report')
  const title = `${head} — ${meta.title || ''}`.trim()
  return `<!doctype html><html lang="${lang}"><head><meta charset="utf-8">` +
    `<title>${_escHtml(title)}</title><style>${_PRINT_CSS}</style></head>` +
    `<body>${_mdToHtml(buildLaudo(meta, r))}</body></html>`
}

export function printLaudoPdf(meta: LaudoMeta, r: RefineResponse) {
  const w = window.open('', '_blank')
  if (!w) {
    alert(meta.lang === 'en'
      ? 'Allow pop-ups to generate the PDF.'
      : 'Permita pop-ups para gerar o PDF.')
    return
  }
  w.document.write(buildLaudoHtml(meta, r))
  w.document.close()
  w.focus()
  setTimeout(() => w.print(), 350)
}

export function downloadLaudo(meta: LaudoMeta, r: RefineResponse) {
  const md = buildLaudo(meta, r)
  const slug = (meta.title || 'laudo').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `laudo-${slug || 'hermeneia'}.md`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
